steps:
  - id: docker_version
    name: docker:20.10-git
    args:
      - version

  - id: docker_system_info
    name: docker:20.10-git
    args:
      - system
      - info

  - id: ls_cloudbuild
    name: docker:20.10-git
    entrypoint: "sh"
    args:
      - -c
      - |
        ls -la ~/.docker

  - id: docker_build_help
    name: docker:20.10-git
    args:
      - build
      - --help

  - id: docker_buildx_help
    name: docker:20.10-git
    args:
      - build
      - --help
    env:
      - "DOCKER_BUILDKIT=1"
